ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "Уфф... Опять этот морок");
ds_queue_enqueue(messages, "Уже в который раз");
ds_queue_enqueue(messages, "Я очнулся и мой взгляд снова приклеился к бескрайней полированной поверхности стола, занимавшего почти весь конфренц-зал");
ds_queue_enqueue(messages, "Профессор всё тараторил. Это, наверное, его мерное бормотание усыпило меня прямо посреди военного брифинга");
ds_queue_enqueue(messages, "Я кемарил, поди, уже минут 10, а Артемоныч все бубнит и бубнит не утухая");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "<Роберт Артемонович>");
ds_queue_enqueue(messages, "Таким образом, собранные в ходе разведывательного вылета биоматериалы позволят нам сделать окончательные выводы о строении и метаболическом цикле внутриглоточных парахитиновых комков и их влиянии на рост кровепровода задних яйцеводов мокротных трубчатых");
ds_queue_enqueue(messages, "<Роберт Артемонович>");
ds_queue_enqueue(messages, "резцов коронарного иглистого тела искуственных беспозвоночных");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "<Подполковник Черепцов>");
ds_queue_enqueue(messages, "Спасибо, Роберт Артемонович. Достаточно. Вы блестяще объяснили задачу нашим пилотам, правда, кое-кто, как я вижу, не уделил достаточного внимания вашим словам");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "<Подполковник Черепцов>");
ds_queue_enqueue(messages, "Лейтенант Гадрберри!");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Я!");
ds_queue_enqueue(messages, "<Подполковник Черепцов>");
ds_queue_enqueue(messages, "Яйцеложе от червя! Повторите-ка, что только что сказал профессор");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "...");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Мммм... ну...");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Ээээ");
ds_queue_enqueue(messages, "<Подполковник Черепцов>");
ds_queue_enqueue(messages, "Оставить! Ясно все с тобой.");
ds_queue_enqueue(messages, "<Подполковник Черепцов>");
ds_queue_enqueue(messages, "Сколько тебе лет-то, сынок?");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "21");
ds_queue_enqueue(messages, "<Подполковник Черепцов>");
ds_queue_enqueue(messages, "О, очко-с! Так ты после интерната, значит?");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Так точно. Выпущен досрочно в связи с атакой Чеврей");
ds_queue_enqueue(messages, "<Подполковник Черепцов>");
ds_queue_enqueue(messages, "Нда-а. Дамплифайеры, желчеглоты и контрактные социопаты");
ds_queue_enqueue(messages, "<Подполковник Черепцов>");
ds_queue_enqueue(messages, "И почему-то весь этот сброд вечно прикомандировывают ко мне в часть");
ds_queue_enqueue(messages, "<Подполковник Черепцов>");
ds_queue_enqueue(messages, "Вот попадешь в плен к Фракции-с");
ds_queue_enqueue(messages, "<Подполковник Черепцов>");
ds_queue_enqueue(messages, "будут они тебя пытать-с, чтобы ты им военную тайну рассказал");
ds_queue_enqueue(messages, "<Подполковник Черепцов>");
ds_queue_enqueue(messages, "А ты не знаешь ни черта");
ds_queue_enqueue(messages, "<Подполковник Черепцов>");
ds_queue_enqueue(messages, "И будешь ты у них умирать, медленно, страшно и за просто так. Они же там во Фракции мастера людей умучивать-с");
ds_queue_enqueue(messages, "<Подполковник Черепцов>");
ds_queue_enqueue(messages, "В общем, плохи твои дела, лейтенант. Ой, как плохи");
ds_queue_enqueue(messages, "Постепенно звпас специфического нравоучительного настроя у подполковника иссяк, и вот он уже зычным голосом командует:");
ds_queue_enqueue(messages, "<Подполковник Черепцов>");
ds_queue_enqueue(messages, "Брифинг окончен! Вольно! Разойдись");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "Командиры и пилоты начали разбредаться, наполняя гулкий зал топотом, шорохом бумаг и шарканием казенной мебели.");
ds_queue_enqueue(messages, "У двухстворчатой двери зала открывалась только одна половина, поэтому я присоедился к скученной подле нее человеской массе и потоптался там добрых пару минут, прежде чем, наконец, вышел в коридор");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "Я деревянной походкой прошел по просторному коридору прямо до кафетерия");
ds_queue_enqueue(messages, "До вылета оставалось около получаса, так что если повезёт, можно будет немного поживиться.");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Blyat'! Можно подумать, этих яйцеголовых вообще можно слушать больше полуминуты");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "По полупустому кафетерию разносился гул и позвякивание кухонных машин, разносивших немного прогорклый, но все же желанный аромат продуктов военного общепита");
ds_queue_enqueue(messages, "Я взял поднос подошел к раздаточному автомату.");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "Автомат высветил на экране сегодняшнее меню.");
ds_queue_enqueue(messages, "Жареные кормовые беспозвоночные под яблочно-абрикосовым соусом, слоновый хлеб и кофе без кофеина");
ds_queue_enqueue(messages, "Что-ж, могло быть и хуже");
ds_queue_enqueue(messages, "Из внутреннего отделения автомата показалась форсунка для кофе");
ds_queue_enqueue(messages, "Я воровато оглянулся и и жестом достал из кармана листок папиросной бумаги.");
ds_queue_enqueue(messages, "Теперь надо внимательно прислушаться к работе автомата");
ds_queue_enqueue(messages, "Шипение");
ds_queue_enqueue(messages, "Три оборота");
ds_queue_enqueue(messages, "Я начинаю бесшумно сворачивать кулёк пальцами одной руки, делая вид, что оправляю борт кителя");
ds_queue_enqueue(messages, "Щелчок, еще два оборота");
ds_queue_enqueue(messages, "Прерывистое шипение");
ds_queue_enqueue(messages, "Уверенным, наглым движением подставляю кулек под форсунку");
ds_queue_enqueue(messages, "Щелчок");
ds_queue_enqueue(messages, "Шуршание");
ds_queue_enqueue(messages, "Еще один пас рукой, достойный профессионального карточного шулера...");
ds_queue_enqueue(messages, "И у меня в кармане целый кулек того, что сложнее всего достать в нашей части");
ds_queue_enqueue(messages, "Сахар");
ds_queue_enqueue(messages, "Да, представьте себе, стоило какому-то яйцеголовому из техцентра заявить, что сахар может привлекать червей и что они чуют его за десятки километров, как его тут же запретили хранить и употреблять вне пищеблока");
ds_queue_enqueue(messages, "Теперь на сахар можно было обменять почти все:");
ds_queue_enqueue(messages, "Cекс, караульную смену, свежие простыни");
ds_queue_enqueue(messages, "Как бы то ни было, дело сделано, сахар в кармане, Ноги привычно понесли меня к нашему столу, откуда мне уже приветственно замахали руками Эрик и Нэнси");
