ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "Уфф... Опять этот морок");
ds_queue_enqueue(messages, "Уже в который раз");
ds_queue_enqueue(messages, "Я очнулся и мой взгляд снова приклеился к бескрайней полированной поверхности стола, занимавшего почти весь конфренц-зал");
ds_queue_enqueue(messages, "Профессор всё тарахтел. Это, наверное, его мерное бормотание усыпило меня прямо посреди военного брифинга");
ds_queue_enqueue(messages, "Я кемарил, поди, уже минут десять, а Артемоныч все бубнит и бубнит не утухая");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "<Роберт Артемонович>");
ds_queue_enqueue(messages, "Таким образом, собранные в ходе разведывательного вылета биоматериалы позволят нам сделать окончательные выводы о строении и метаболическом цикле внутриглоточных парахитиновых комков и их влиянии на рост кровепровода задних яйцеводов мокротных трубчатых");
ds_queue_enqueue(messages, "<Роберт Артемонович>");
ds_queue_enqueue(messages, "резцов коронарного иглистого тела искуственных беспозвоночных");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "<Подполковник Черепцов>");
ds_queue_enqueue(messages, "Спасибо, Роберт Артемонович. Достаточно. Вы блестяще объяснили задачу нашим пилотам, правда, кое-кто, как я вижу, не уделил достаточного внимания вашим словам");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "<Подполковник Черепцов>");
ds_queue_enqueue(messages, "Лейтенант Гадрберри!");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Я!");
ds_queue_enqueue(messages, "<Подполковник Черепцов>");
ds_queue_enqueue(messages, "Яйцеложе от червя! Повторите-ка, что только что сказал профессор");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "...");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Мммм... ну...");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Ээээ");
ds_queue_enqueue(messages, "<Подполковник Черепцов>");
ds_queue_enqueue(messages, "Оставить! Ясно все с тобой.");
ds_queue_enqueue(messages, "<Подполковник Черепцов>");
ds_queue_enqueue(messages, "Сколько тебе лет-то, сынок?");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "21");
ds_queue_enqueue(messages, "<Подполковник Черепцов>");
ds_queue_enqueue(messages, "О, очко-с! Так ты после интерната, значит?");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Так точно. Выпущен досрочно в связи с атакой Чеврей");
ds_queue_enqueue(messages, "<Подполковник Черепцов>");
ds_queue_enqueue(messages, "Нда-а. Дамплифайеры, желчеглоты и контрактные социопаты");
ds_queue_enqueue(messages, "<Подполковник Черепцов>");
ds_queue_enqueue(messages, "И почему-то весь этот сброд вечно прикомандировывают ко мне в часть");
ds_queue_enqueue(messages, "<Подполковник Черепцов>");
ds_queue_enqueue(messages, "Вот попадешь в плен к Фракции-с");
ds_queue_enqueue(messages, "<Подполковник Черепцов>");
ds_queue_enqueue(messages, "будут они тебя пытать-с, чтобы ты им военную тайну рассказал");
ds_queue_enqueue(messages, "<Подполковник Черепцов>");
ds_queue_enqueue(messages, "А ты не знаешь ни черта");
ds_queue_enqueue(messages, "<Подполковник Черепцов>");
ds_queue_enqueue(messages, "И будешь ты у них умирать, медленно, страшно и за просто так. Они же там во Фракции мастера людей умучивать-с");
ds_queue_enqueue(messages, "<Подполковник Черепцов>");
ds_queue_enqueue(messages, "В общем, плохи твои дела, лейтенант. Ой, как плохи");
ds_queue_enqueue(messages, "Постепенно запас специфического нравоучительного настроя у подполковника иссяк, и вот он уже зычным голосом командует:");
ds_queue_enqueue(messages, "<Подполковник Черепцов>");
ds_queue_enqueue(messages, "Брифинг окончен! Вольно! Разойдись");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "Командиры и пилоты начали разбредаться, наполняя гулкий зал топотом, шорохом бумаг и шарканием казенной мебели.");
ds_queue_enqueue(messages, "У двухстворчатой двери зала открывалась только одна половина, поэтому я присоедился к скученной подле нее человеской массе и потоптался там добрых пару минут, прежде чем, наконец, вышел в коридор");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "Я деревянной походкой прошел по просторному коридору прямо до кафетерия");
ds_queue_enqueue(messages, "До вылета оставалось около получаса, так что если повезёт, можно будет немного поживиться.");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Blyat'! Можно подумать, этих яйцеголовых вообще можно слушать больше полуминуты");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "По полупустому кафетерию разносился гул и позвякивание кухонных машин, разносивших немного прогорклый, но все же желанный аромат продуктов военного общепита");
ds_queue_enqueue(messages, "Я взял поднос подошел к раздаточному автомату");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "Автомат высветил на экране сегодняшнее меню");
ds_queue_enqueue(messages, "Жареные кормовые беспозвоночные под яблочно-абрикосовым соусом, слоновый хлеб и кофе без кофеина");
ds_queue_enqueue(messages, "Что-ж, могло быть и хуже");
ds_queue_enqueue(messages, "Из внутреннего отделения автомата показалась форсунка для кофе");
ds_queue_enqueue(messages, "Я воровато оглянулся и и жестом достал из кармана листок папиросной бумаги.");
ds_queue_enqueue(messages, "Теперь надо внимательно прислушаться к работе автомата");
ds_queue_enqueue(messages, "Шипение...");
ds_queue_enqueue(messages, "Три оборота...");
ds_queue_enqueue(messages, "Я начинаю бесшумно сворачивать кулёк пальцами одной руки, делая вид, что оправляю борт кителя");
ds_queue_enqueue(messages, "Щелчок, еще два оборота");
ds_queue_enqueue(messages, "Прерывистое шипение...");
ds_queue_enqueue(messages, "Уверенным, наглым движением подставляю кулек под форсунку");
ds_queue_enqueue(messages, "Щелчок...");
ds_queue_enqueue(messages, "Шуршание...");
ds_queue_enqueue(messages, "Еще один пас рукой, достойный профессионального карточного шулера и...");
ds_queue_enqueue(messages, "У меня в кармане целый кулек того, что сложнее всего достать в нашей части");
ds_queue_enqueue(messages, "Сахар...");
ds_queue_enqueue(messages, "Да, представьте себе, стоило какому-то яйцеголовому из техцентра заявить, что сахар может привлекать червей и что они чуют его за десятки километров, как его тут же запретили хранить и употреблять вне пищеблока");
ds_queue_enqueue(messages, "Теперь на сахар можно было обменять почти все:");
ds_queue_enqueue(messages, "Cекс, караульную смену, свежие простыни");
ds_queue_enqueue(messages, "Как бы то ни было, дело сделано, сахар в кармане, Ноги привычно понесли меня к нашему столу, откуда мне уже приветственно замахали руками Эрик и Нэнси");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "<Эрик и Нэнси>");
ds_queue_enqueue(messages, "Cтив, ну что ты возился так долго, а?");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Секрет");
ds_queue_enqueue(messages, "Эрик и я обменялись крепким рукопожатием");
ds_queue_enqueue(messages, "Командование части не поощаряло глубокие взаимные эмоциональные привязанности братьев и сестер по оружию, поэтому мы с Нэнси ограничились просто теплыми объятиями");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "<Эрик>");
ds_queue_enqueue(messages, "Эй, Стив! Сегодня опять боевой вылет?");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Патрульно-разведывательный");
ds_queue_enqueue(messages, "<Эрик>");
ds_queue_enqueue(messages, "Не завидую, опять нарезать круги по мертвому городу");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Ага. И собирать в баки червячье дерьмо для яйцеголовых. Зато прилечу-то хоть пораньше, так что, может быть, вечерком еще потусуем. Ты с нами, если что?");
ds_queue_enqueue(messages, "<Эрик>");
ds_queue_enqueue(messages, "Неа, я сегодня репетирую. Там смотрины намечаются - опять эти ковырялки разучивать");
ds_queue_enqueue(messages, "Эрика недавно взяли в полковой оркестр");
ds_queue_enqueue(messages, "Место хлебное, но его бесило откладывать собстенные репетиции, ради песен военных лет, которые он называл не иначе как `ковырялками`");
ds_queue_enqueue(messages, "Тут стоит сделать небольшое отступление");
ds_queue_enqueue(messages, "Меня вообще дружелюбным человеком не назвовешь, даже по военным меркам");
ds_queue_enqueue(messages, "Но в этих двоих было что-такое...");
ds_queue_enqueue(messages, "Хм, проще сказать чего в них не было");
ds_queue_enqueue(messages, "Не было всей этой мягкотелости и напыщенности - неотъемлемой черты выпускников обычных, непенецентарных, училиш, где твои недоброжелатели, максимум, натрут тебе нос сапожной биоваксой, пока ты спишь");
ds_queue_enqueue(messages, "Ну, или не нос");
ds_queue_enqueue(messages, "Короче, всех эти сынуль и роднуль своих пафосных штабных папаш");
ds_queue_enqueue(messages, "Надеюсь, вы поняли");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "<Нэнси>");
ds_queue_enqueue(messages, "С тобой все порядке? Череп на тебя так орал, что я в коридоре слышала. Сразу поняла, что это он 	тебе");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "А, ерунда, не беспокойся, ты же его знаешь");
ds_queue_enqueue(messages, "<Нэнси>");
ds_queue_enqueue(messages, "Говорят, он просто недолюбливает интернатских");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Ндаа");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Тогда я явно не тот человек, кто сможет изменить его стереотипы насчет этого");
ds_queue_enqueue(messages, "Наша дружба и любовь были прекрасны");
ds_queue_enqueue(messages, "Пока их не начала разъдать _желчь_");
ds_queue_enqueue(messages, "Вот и сейчас, как я не старался, увильнуть, тема _желчи_ довольно быстро всплыла в разговоре");
ds_queue_enqueue(messages, "<Нэнси>");
ds_queue_enqueue(messages, "Ты уже принимал таблетки? Они помогли?");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Не помогли. Там пока все такое же ссохшееся, ничего не выдоишь");
ds_queue_enqueue(messages, "Нехорошо");
ds_queue_enqueue(messages, "Ох, как нехорошо врать боевым товарищам");
ds_queue_enqueue(messages, "Нэнси побледнела, взгляд мнговенно погас. Было видно, каких усилий ей стоило разом не потерять самообладание");
ds_queue_enqueue(messages, "Видеть любимого человека таким");
ds_queue_enqueue(messages, "Врагу не пожелаю");
ds_queue_enqueue(messages, "<Нэнси>");
ds_queue_enqueue(messages, "Ясно");
ds_queue_enqueue(messages, "Я отчетливо ощущал, как она старается чтобы голос ее не дрожал");
ds_queue_enqueue(messages, "<Нэнси>");
ds_queue_enqueue(messages, "Наверное, нужно еще немного времени, чтобы корки размокли изнутри");
ds_queue_enqueue(messages, "<Нэнси>");
ds_queue_enqueue(messages, "Если что, я спрошу у своего источника что-то посильнее");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Хорошо, Нэнс, только соблюдай конспирацию");
ds_queue_enqueue(messages, "<Нэнси>");
ds_queue_enqueue(messages, "Не волнуйся, я описала твои симптомы, как травму от стрекательной ложноножки");
ds_queue_enqueue(messages, "<Нэнси>");
ds_queue_enqueue(messages, "Никто ничего не узнает");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Тогда нормально");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Эй, Рыжий!");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "А не ты ли, кстати, в последний раз, храбрился, что достанешь у Артемоныча бюретки, чтобы желчь было удобнее цедить?");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "<Эрик>");
ds_queue_enqueue(messages, "Я в лабораторию к этому мяснику в трезвом виде ни ногой");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Что ж, значит чуть позже");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Ладно, друзья, я тогда погнал в патруль. Если что, вечером увидимся");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "<Нэнси>");
ds_queue_enqueue(messages, "Удачи, Стив");
ds_queue_enqueue(messages, "<Нэнси>");
ds_queue_enqueue(messages, "Будь осторожен");
ds_queue_enqueue(messages, "<Нэнси>");
ds_queue_enqueue(messages, "Вечером буду ждать тебя на площадке, как обычно");
ds_queue_enqueue(messages, "Раньше, произнося эти слова, Нэнс мне игриво подмигивала, но теперь она произносила их, скорее, обреченно");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "<Эрик>");
ds_queue_enqueue(messages, "Давай. Как желчь будет, всю не выдувай сразу, нам оставь немножно хоть");
ds_queue_enqueue(messages, "Эрик пытался делать вид, что шутит");
ds_queue_enqueue(messages, "Я сделал вид, что принял это за шутку");
ds_queue_enqueue(messages, "Вот такая стала наша дружба");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "Дожевывая на ходу остатки слонового хлеба, я быстрым шагом направился из столовой на транспортную площадку");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "На транспортной площадке, я запрыгнул на первый же свободный робоскутер, который, наконец, повез меня наружу");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "Робоскутер плелся со скоростью улитки, как будто стараясь получше прожарить меня по дороге к ангарам");
ds_queue_enqueue(messages, "Отливающий неоном край гравиплатформы почти касаося горизонта");
ds_queue_enqueue(messages, "***Пик-пик-пик***");
ds_queue_enqueue(messages, "Расчетное время прибытия: 5 минут");
ds_queue_enqueue(messages, "Поездка на каре от основного корпуса к ангарам - это отдельная изощренная форма пытки, практикуемая в нашей части");
ds_queue_enqueue(messages, "Но для меня это те редкие минуты уставной жизни, когда ты можешь побыть полностью один и не раздражаться от ничьих назойливых глаз");
ds_queue_enqueue(messages, "Я нащупал в кармане сверток с сахаром и осмотрел язву на своей ладони");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "Кратерообразные язвенные выросты");
ds_queue_enqueue(messages, "По краям видоизменных тканей поблескивали капли _желчи_");
ds_queue_enqueue(messages, "Я врал. Таблетки помогли");
ds_queue_enqueue(messages, "Чуть присыпав язву сахаром из свертка, я приложил ладонь к губам и принялся высасывать из нее желчь");
ds_queue_enqueue(messages, "Сахар служил органическим катализатором а задоно и делал вкус этой дряни хоть сколько-нибудь сносным");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "Пустырь");
ds_queue_enqueue(messages, "Площадка");
ds_queue_enqueue(messages, "Небо");
ds_queue_enqueue(messages, "Все разом вспыхнуло миллионами огней");
ds_queue_enqueue(messages, "Мой слух будто бы наполнил очищающий звон тысяч литых пиал");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "Пока я ехал, мою машину уже выкатили из ангара");
ds_queue_enqueue(messages, "Жуки суетливо сновали туда-сюда, выдергивая из гнезд последние питательные и диагностические шланги");
ds_queue_enqueue(messages, "Ритмично рычали, прогреваясь, эй-джи генераторы");
ds_queue_enqueue(messages, "Товарищ лейтенант, сэр");
ds_queue_enqueue(messages, "Боевая эй-джи машина СГ-145 готова к патрульному вылету");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "Пилотское кресло встретило меня затягивающими на запястьях и икрах датчиками витальных показателей");
ds_queue_enqueue(messages, "Приборная панель зажгла гирлянды индикаторов, калибровочных сеток и визоров");
ds_queue_enqueue(messages, "Я - лейтенант Стивен Гардберри");
ds_queue_enqueue(messages, "Гравитекк-пилот военно-воздушных сил Северной Агломерации");
ds_queue_enqueue(messages, "И это мой очередной дерьмовый день");
ds_queue_enqueue(messages, "Наслаждайтесь");
