ds_queue_enqueue(messages, "<o_sprite_dispatcher>");
ds_queue_enqueue(messages, "Перед вылетом необходима проверка основных функциональных узлов вашей боевой машины");
ds_queue_enqueue(messages, "<o_sprite_dispatcher>");
ds_queue_enqueue(messages, "Шаг первый - функциональность инжереной башни (она отмечена зеленым цветом на вашем тактическом визоре)");
ds_queue_enqueue(messages, "<o_sprite_dispatcher>");
ds_queue_enqueue(messages, "Установите инженерную (зеленую) башню гравитанка на зеленую платформу-маяк, чтобы открыть ворота ангара");
ds_queue_enqueue(messages, "<o_sprite_dispatcher>");
ds_queue_enqueue(messages, "И поторапливайся там, а то сегодня в офицерском клубе вечер одиноких сердец");
ds_queue_enqueue(messages, "<o_sprite_dispatcher>");
ds_queue_enqueue(messages, "Добро пожаловать в патруль, катись он червём!");
ds_queue_enqueue(messages, "<o_sprite_dispatcher>");
ds_queue_enqueue(messages, "Перед вылетом необходима проверка основных функциональных узлов вашей боевой машины");
ds_queue_enqueue(messages, "<o_sprite_dispatcher>");
ds_queue_enqueue(messages, "Шаг первый - функциональность инжереной башни (она отмечена зеленым цветом на вашем тактическом визоре)");
ds_queue_enqueue(messages, "<o_sprite_dispatcher>");
ds_queue_enqueue(messages, "Установите инженерную (зеленую) башню гравитанка на зеленую платформу-маяк, чтобы открыть ворота ангара");
ds_queue_enqueue(messages, "<o_sprite_dispatcher>");
ds_queue_enqueue(messages, "И поторапливайся там, а то сегодня в офицерском клубе вечер одиноких сердец");
