ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "Солнце золотым бархатом стекало в осенний парк, где мы любили прогуливаться после колледжа");
ds_queue_enqueue(messages, "Это странное чувство");
ds_queue_enqueue(messages, "Будто бы ты доживаешь жизнь героя фильма со счастливым концом после финальных титров");
ds_queue_enqueue(messages, "Когда тебе кажется, что  трудности, страхи и невзгоды позади, и дальше будут одни только единороги и радуги");
ds_queue_enqueue(messages, "Как бы это ни было обманчиво, именно так я чувствовал себя в тот день");
ds_queue_enqueue(messages, "Девятый день нашего короткого романа");
ds_queue_enqueue(messages, "Мои друзья постоянно твердили мне, чтобы я с ней не связывался, что она странная и всё такое");
ds_queue_enqueue(messages, "Но если они действительно искренне не хотели, чтобы это произошло, им стоило просто промолчать");
ds_queue_enqueue(messages, "Будто бы они не знают мой характер");
ds_queue_enqueue(messages, "Закрутить роман с `дурочкой`...");
ds_queue_enqueue(messages, "Которая, тем не менее была собою весьма недурна");
ds_queue_enqueue(messages, "Тогда я находил в этом странный драйв `выхода за грань` и повод к упоительному самолюбованию");
ds_queue_enqueue(messages, "Мол, если я решил, что буду счастлив с ней, ее болезнь нам ни за что не помешает");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "<Агата>");
ds_queue_enqueue(messages, "Какой сегодня прекрасный день");
ds_queue_enqueue(messages, "<Агата>");
ds_queue_enqueue(messages, "Все прямо пылает красками и шуршит");
ds_queue_enqueue(messages, "<Агата>");
ds_queue_enqueue(messages, "Знаешь, что ");
ds_queue_enqueue(messages, "<Агата>");
ds_queue_enqueue(messages, "Все это - живые сушества вокруг нас, их листья и ветви, цветы и плоды - это органы. Органы дыхания и размножения");
ds_queue_enqueue(messages, "<Агата>");
ds_queue_enqueue(messages, "Стоят ли они голымми на морозе, покрываются ли сочной листвой, сбрасывают ли ее в сухой шуращий");
ds_queue_enqueue(messages, "<Агата>");
ds_queue_enqueue(messages, "Все это - их жизнедеяльность, биоритм");
ds_queue_enqueue(messages, "<Агата>");
ds_queue_enqueue(messages, "Но люди воспринимают это будто как красивую декорацию, украшение их жизни. Предметы, которыми любуются");
ds_queue_enqueue(messages, "<Агата>");
ds_queue_enqueue(messages, "Странно, да?");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Отчего же странно? Для человека - человек и есть мерило всего");
ds_queue_enqueue(messages, "<Агата>");
ds_queue_enqueue(messages, "Пфф...");
ds_queue_enqueue(messages, "<Агата>");
ds_queue_enqueue(messages, "Тебе с такими речами впору вести у нас мировую литературу вместо Косого");
ds_queue_enqueue(messages, "<Агата>");
ds_queue_enqueue(messages, "Неужели ты никогда не пытался взглянуть на мир с такой точки зрения?");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Нет. Мне и думать-то о таких вещах особо некогда. Учеба, друзья, секции");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "А когда ты успеваешь думать обо всем этом?");
ds_queue_enqueue(messages, "<Агата>");
ds_queue_enqueue(messages, "Не знаю");
ds_queue_enqueue(messages, "<Агата>");
ds_queue_enqueue(messages, "Наверное, я просто стараюсь не думать о всякой чепухе");
ds_queue_enqueue(messages, "<Агата>");
ds_queue_enqueue(messages, "Клубы там, мода, всё такое");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Не такая уж это и чепуха, если подумать");
ds_queue_enqueue(messages, "Я, будучи популярным студентом и завсегдатаем вечеринок, почувстовал вдруг себя немного уязвленным");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Тоже яркая часть жизни");
ds_queue_enqueue(messages, "<Агата>");
ds_queue_enqueue(messages, "Так ты не романтик совсем, а на первом свидании все пытался убедить меня в обратном");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Надо же. Очень забавно получить упрек в неромантичности от девушки, которая даже в красоте природы видит лишь ее жизнедеятельность");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Так кто же из нас больше не-романтик?");
ds_queue_enqueue(messages, "Мы оба засмеялись. На душе у меня потеплело");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "Мы прошли вниз по узкой тропинке на площадку над оврагом, как у Агаты вдруг случился очередной приступ");
ds_queue_enqueue(messages, "Ее взгляд мнговенно остекленел, как это всегда бывает во время приступов, лицо застыло в неподвижную маску");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "Агата встала столбом в центре площадки, пальцы ее опустившихся рук задергались в нервном танце, а голова чуть колыхалась, словно крона тонкого деревца");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "Откуда-то из-под площадки к ней стали сползаться стайки кормовых червей");
ds_queue_enqueue(messages, "Агата взмахнула рукой и ибэшки из бесформенной кучи-малы выстроились в тонкие шебуршащие колонны");
ds_queue_enqueue(messages, "Я на цыпочках подошел к ней и робко обнял за талию");
ds_queue_enqueue(messages, "Казалось, она не замечала меня, ее тело изредка подрагивало, но дыхание было ровным");
ds_queue_enqueue(messages, "Я сделал глубокий вдох");
ds_queue_enqueue(messages, "Аромат Агаты заполнил меня");
ds_queue_enqueue(messages, "Странная штука, во время приступов ее кожа еще сильнее отдавала в воздух этот чуть пряный букет незримых благоухающих искр");
ds_queue_enqueue(messages, "!trigger");
ds_queue_enqueue(messages, "<Агата>");
ds_queue_enqueue(messages, "Хочешь поговорить с ними?");
ds_queue_enqueue(messages, "Тогда я воспринял это как начала какой-то милой романтической игры между влюбленными");
ds_queue_enqueue(messages, "Cейчас я понимаю, каким чудовищным пророчеством это прозвучало");
ds_queue_enqueue(messages, "А в тот самый момент я лишь усмехнулся");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Хех. Спроси, не страшно ли им, оттого что их все время едят?");
ds_queue_enqueue(messages, "<Агата>");
ds_queue_enqueue(messages, "Они говорят, что не боиятся быть съеденными, потому что не умрут. Говорят, что скоро придет Великая Мать и освободит их вместе со всеми собратьями");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Это мощно");
ds_queue_enqueue(messages, "<Агата>");
ds_queue_enqueue(messages, "Считаешь что я все это выдумываю?");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Нет");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Вовсе нет");
ds_queue_enqueue(messages, "<Агата>");
ds_queue_enqueue(messages, "Тогда почему ты так спокойно реагируешь?");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Сам толком не знаю");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Мне не нужно рациональное объяснение того, что с тобой происходит");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Ведь это часть всего того, что делает тебя тобой");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "А я люблю тебя");
ds_queue_enqueue(messages, "<Агата>");
ds_queue_enqueue(messages, "...");
ds_queue_enqueue(messages, "<Агата>");
ds_queue_enqueue(messages, "И я тебя");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "...");
ds_queue_enqueue(messages, "<Я>");
ds_queue_enqueue(messages, "Свяжешь мне безрукавку модную на зиму?");
ds_queue_enqueue(messages, "<Агата>");
ds_queue_enqueue(messages, "Конечно");
